name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to FTP server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.WEBSITE_FTP_SERVER }}
          username: ${{ secrets.WEBSITE_FTP_USERNAME }}
          password: ${{ secrets.WEBSITE_FTP_PASSWORD }}
          server-dir: ${{ secrets.WEBSITE_FTP_SERVER_DIR }}
